# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20250514_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('Monastic', 'Monastic'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Plan creator', 'Plan creator'), ('regular user', 'regular user'), ('Reader', 'Reader')], max_length=20),
        ),
    ]
